"""Add reset_token_hash

Revision ID: dc3e8e873c54
Revises: b4aa5aa5f0d8
Create Date: 2026-08-31 23:14:34.157319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3e8e873c54'
down_revision: Union[str, Sequence[str], None] = 'b4aa5aa5f0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_challenges', sa.Column('reset_token_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_challenges', 'reset_token_hash')
    # ### end Alembic commands ###
